#!/bin/sh
if [ "$1" = "" ]; then
	echo -n "Please enter the commit message: "
	read message
	if ! [ "$message" ]; then
		message="Random update"
	fi
else
	message="$@"
fi
git fetch --quiet
git status
git add -A
git diff --quiet && git diff --staged --quiet || (echo && echo "Adding commit \"$message\"..." && git commit -am "$message")
git pull
git push

