#!/bin/sh
git config --local --unset credential.helper
git config --global --unset credential.helper
git config --global credential.helper "store"
git config --global credential.helper "cache --timeout=86400"

