#!/bin/sh
git config --global --unset credential.helper
if git rev-parse HEAD >/dev/null 2>&1; then
	git config --local --unset credential.helper
fi
git config --global credential.helper "cache --timeout=86400"
git config --global credential.helper "store"

