#!/bin/sh

repo_url="$@"
while [ "$repo_url" = "" ]; do
	echo -n "Please enter a repository URL: "
	read repo_url
done
reponame=$(basename -s ".git" $repo_url)

# Create a new local repository from scratch
rm -rf .git
git init

# Find the default name of local branch
master=$(cat .git/HEAD | cut -d/ -f3)

# Define the remote origin
git remote add origin $repo_url

# Find the name of remote branch
branch=$(git remote show $repo_url | grep " HEAD branch: " | tr -s \ | sed "s/ HEAD branch: //")
if [ $branch = "(unknown)" ]; then
	# No content yet on remote branch

	# Create an initial commit
	git add -A
	git commit --allow-empty -m "Initial commit"

	# Find the name of the local branch
	branch="$(cat .git/HEAD | cut -d/ -f3)"

	# Push to remote
	git push --set-upstream origin $branch

else
	# The remote branch has content

	# Create an initial commit
	git add -A
	git commit --allow-empty -m "First upload"

	# Rename the local branch
	git branch -M $branch

	# Pull from remote
	git remote update 2>/dev/null
	if git remote set-head origin -a >/dev/null 2>&1; then
		if git log -p | grep diff >/dev/null; then
			git pull --rebase origin $branch -X theirs
		else
			git pull --rebase origin $branch
		fi
	fi

	# Push to remote
	git push --set-upstream origin $branch

fi

