#!/bin/sh

repo_url="$@"
while [ "$repo_url" = "" ]; do
	echo -n "Please enter a repository URL: "
	read repo_url
done
reponame=$(basename -s ".git" $repo_url)

if [ -f "README.md" ]; then
	tmpfile=$(mktemp)
	mv "README.md" "$tmpfile"
fi

# Create a new local repository from scratch
rm -rf .git
git init

# Find the default name of local branch
master=$(cat .git/HEAD | cut -d/ -f3)

# Define the remote origin
git remote add origin $repo_url

# Find the name of remote branch
branch=$(git remote show $repo_url | grep " HEAD branch: " | tr -s \ | sed "s/ HEAD branch: //")

# Create an empty commit
git commit --allow-empty -m "[Empty]"

if [ $branch = "(unknown)" ]; then
	# No content yet on remote branch

	# Use the name of the local branch
	branch="$(cat .git/HEAD | cut -d/ -f3)"

else
	# The remote branch has content

	# Rename the local branch
	git branch -M $branch

	# Pull from remote, may overwrite local files
	git remote update 2>/dev/null
	if git remote set-head origin -a >/dev/null 2>&1; then
		git reset --hard origin/$branch >/dev/null
		git pull --rebase origin $branch
	fi

fi

# Push to remote
git push --set-upstream origin $branch

if [ -f "$tmpfile" ]; then
	mv "$tmpfile" "README.md"
	rm -f "$tmpfile"
fi

