#!/bin/sh

fetch=$(git fetch 2>&1)

exitcode="$?"
if [ "$exitcode" = "0" ]; then

	git status
	git add -A

	if ! ( git diff --quiet && git diff --quiet --staged ) ; then

		if [ "$1" = "" ]; then
			echo -n "Please enter the commit message: "
			read message
			if [ "$message" = "" ]; then
				message="Random update"
			fi
		else
			message="$@"
		fi

		echo "Adding commit \"$message\"..."
		git commit -am "$message"

		commit=true
	fi

	if [ "$fetch" ]; then
		git pull
	fi

	if [ "$commit" ]; then
		git push
	fi

else
	>&2 echo "$fetch"
	exit $exitcode
fi

